// <auto-generated />
using System;
using MeterTest.Source.SQLite.ParaConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeterTest.Migrations.ParaConfigTableDb
{
    [DbContext(typeof(ParaConfigTableDbContext))]
    [Migration("20211209072236_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigDataId", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DataArray")
                        .HasColumnType("BLOB");

                    b.Property<string>("ConfigTableName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWritable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParaConfigTableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "DataArray");

                    b.HasIndex("ParaConfigTableName");

                    b.ToTable("DataIds");
                });

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigTable", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ParaConfigTables");
                });

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigDataId", b =>
                {
                    b.HasOne("MeterTest.Source.SQLite.ParaConfig.ParaConfigTable", null)
                        .WithMany("DataIds")
                        .HasForeignKey("ParaConfigTableName");
                });

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigTable", b =>
                {
                    b.Navigation("DataIds");
                });
#pragma warning restore 612, 618
        }
    }
}
