// <auto-generated />
using System;
using MeterTest.Source.SQLite.ParaConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeterTest.Migrations.ParaConfigTableDb
{
    [DbContext(typeof(ParaConfigTableDbContext))]
    partial class ParaConfigTableDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigDataId", b =>
                {
                    b.Property<string>("ConfigTableName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DataArray")
                        .HasColumnType("BLOB");

                    b.Property<int>("DataBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWritable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigTableName", "Id", "DataArray");

                    b.ToTable("DataIds");
                });

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigTable", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ParaConfigTables");
                });

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigDataId", b =>
                {
                    b.HasOne("MeterTest.Source.SQLite.ParaConfig.ParaConfigTable", "table")
                        .WithMany("DataIds")
                        .HasForeignKey("ConfigTableName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("table");
                });

            modelBuilder.Entity("MeterTest.Source.SQLite.ParaConfig.ParaConfigTable", b =>
                {
                    b.Navigation("DataIds");
                });
#pragma warning restore 612, 618
        }
    }
}
